#!/usr/bin/expect 
set password "Huawei12#$"
set ip  "10.3.23.46"
set ips [lrange $argv 0 0]
spawn ssh zxy@$ips sudo su
    expect {
       "(yes/no)" {send "yes\r"}
       "*assword" {send "$password\r"}
     }
    expect "]#"                          #执行完sudo su 执行后继续执行的命令
    send "ntpdate $ip\r"
    send "exit\r"
expect eof

    #interact                          #登录不退出命令
exit
